[package]
name = "snake"
version = "0.1.0"
authors = ["Jake Van Alstyne ☥ <j@jva.lol>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blitzkit = "0.4"
glam = "0.33"
rodio = { version = "0.22", default-features = false, features = ["wav"] }
rand = "0.8.3"
